### ISSUE TITLE
Vein not appearing after updating / cannot delete bad vein

### ISSUE THREAD

**Issue by PolkageistHS** [SinTh0r4s/VisualProspecting#12]
I updated to visualprospecting-1.7.10-latest-19-g9570f39.jar (from http://jenkins.usrv.eu:8080/job/Visual-Prospecting/16/) on my client and server and set the configs to recache=true.  There's a salt vein next to my base in the overworld that I just recently discovered, but I couldn't get it to register with VP.  I've tried with ores directly in the ore chunk as well as ores in adjacent chunks.  

I then cheated in one of those crappy MV prospectors to see if I could get it to show up on the map before I mined it out.  Unfortunately, that seems to have marked the vein as a Gold vein, possibly because the vein just north of it is Gold and it's at the world axis so they kind of overlap?  Now the Salt vein is marked as Gold and I have no way to remove it to try again.  

![image](https://user-images.githubusercontent.com/9247381/143964833-f353062d-0297-4458-b44d-f242a9204094.png)
The Gold vein with my player icon should actually be Salt, not Gold.

**Comment by SinTh0r4s** [comment]
> ...possibly because the vein just north of it is Gold and it's at the world axis so they kind of overlap?

Correct. GT uses a semi-optimal algorithm to determine ore vein centers. This overlapping (one chunk closer) is the result.

Did you mine that salt vein pretty much completely?

**Comment by PolkageistHS** [comment]
Mostly, yes.  I left the bottom layer intact so I'd have something to maybe test a new version on later.

**Comment by SinTh0r4s** [comment]
Visual Prospecting needs to guess the layer based on existing ores. Sadly, GT does not save the location and identity of generated veins. I did place a hook, but it can only catch world generation after the mod was added/after the last forced cache regeneration (via config).

It is acceptable behaviour for me. Just mark it depleted and move on ;-)
