### ISSUE TITLE
compatible with stable ? 

### ISSUE THREAD

**Issue by thibaut-fagart** [SinTh0r4s/VisualProspecting#17]
I stumbled upon this mod while googling for GTNH prospection, and tried to install it on my stable 2.1.1.0 (installed from MultiMC from the technic "store") world, as it seems it would help dramatically with oil field prospection.

It works partially : thaumcraft nodes show up, ore veins show up (although they seem shifted), but since i installed it, I'm not able to copy data to datasticks from the seismic prospector,

I installed 1.0.22b, 
Uninstalling allows to get "prospection data" again

**Comment by SinTh0r4s** [comment]
Thanks for the issue! There was a rewrite of underground fluids in GTNH and I did indeed forget to keep compatibility with the old GT. Here is a new release for you: https://github.com/SinTh0r4s/VisualProspecting/releases/tag/1.0.23b

Could you do me a favour and verify the fix by comparing it to a GT Scanner? Thanks!

**Comment by thibaut-fagart** [comment]
Thanks for the quick fix and feedback, I appreciate it (and the quality of your code/documentation sems nice, even though i'm not familiar with minecraft programming). I'll be testing it soon.
if you have a minute i have a question which i didn't see an answer : i have a few prospection book already, will reading them add the info to your mod, or do i need to use the seismic prospector ?

**Comment by SinTh0r4s** [comment]
You're welcome. Sadly, the way I implemented it you need to create a new book. The book will tell you on the first page (down at the end) if it is compatible/synchronized with VisualProspecting. Old books sadly won't work.

**Comment by thibaut-fagart** [comment]
good job, it definitely works with the seismic prospector now
haven't tested the portable one yet, mine is dead, will update later

Thanks for the very quick fix !

**Comment by SinTh0r4s** [comment]
Good to know! The new GT underground fluids generate the fluids at different locations. So the GT Scanner could show something different. If so: open another issue, but I used the old code from before. So it should be all fine. Have fun!
