### ISSUE TITLE
Rendering on Minimap

### ISSUE THREAD

**Issue by SinTh0r4s** [SinTh0r4s/VisualProspecting#20]
@kumquat-ir 
I've added MiniMap rendering to JourneyMap. Are you interested to getting it to Xaero as well? More of an FYI ;-)

**Comment by kumquat-ir** [comment]
good news: just jamming the existing rendering code in there *mostly* works

![2022-01-10_14 45 57](https://user-images.githubusercontent.com/66188216/148829162-6ad1df30-7e17-428c-8b51-95d4ac4b1227.png)

culling, rotation, text rendering, and actually displaying it all the time need some work

**Comment by SinTh0r4s** [comment]
Awesome! Already looking good! I would keep it with the toggle in the Fullscreen map. So it will only display if active. But besides offset, culling and rotation it looks shippable :D
